<?php include ('header.php');?>
<section>
	<div class="container">
		<div class="col-lg-12 col-md-12 col-sm-12">
			<div class="header_tittal_tab">
				<h3>TERMS OF USE</h3>
			<div>
			</div class="main_terms_use">
				<p><strong><span style="font-size:24.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">TERMS OF USE</span></span></strong></p>

<p><strong><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">Important:</span></span></strong><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"> Please ensure that you read and understand all these Terms of Use before you use the Service. If you do not accept any of the Terms of Use, then please do not use the Website or avail any of the services being provided therein. By using this Service, you agree that you have read, understood, accepted and agreed with the Terms of Use. You further agree to the representations made by yourself below. If you do not agree to or fall within the Terms of Use of the Service (as defined below) and wish to discontinue using the Service, please do not continue using this Application or Service.</span></span></p>

<div style="margin-bottom:.0001pt; text-align:center">
<hr /></div>

<p>&nbsp;</p>

<p><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">The Terms of Use stated herein (collectively, the &quot;Terms of Use&quot; or this &quot;Agreement&quot;) constitute a legal agreement between you and <strong>Solution hub</strong>. In order to use the Service (each as defined below) you must agree to the Terms of Use that are set out below. By using the mobile application supplied to you by the GoAid (the &quot;Application&quot;), and downloading, installing or using any associated software supplied by GoAid (&quot;the Software&quot;) which overall purpose is to enable persons seeking Ambulance Transportation Services to be matched with an independent provider of Ambulance Transportation Services <strong>(&ldquo;Transportation Provider(s)&rdquo;)</strong> (collectively, the &quot;Service&quot;), you hereby expressly acknowledge and agree to be bound by the Terms of Use, and any future amendments and additions to this Terms of Use as published from time to time at <u><span style="color:blue">http:// GoAid.in</span></u> or through the Application. </span></span></p>

<p><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">This document is an electronic record in terms of Information Technology Act, 2000 and rules thereunder as applicable and the provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures. This Agreement is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use.</span></span></p>

<p><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">GoAid is a technology GoAid that does not provide any Ambulance Transportation Services and is not an ambulance provider. GoAid is merely an aggregator. It is up to the Transportation Provider to offer ambulance services to you and it is up to you to accept such transportation services. The service of GoAid is to link you with such Transportation Providers through the licensed use of its mobile application and/or through its online portal at </span></span><a href="https://medulance.com/terms"><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><span style="color:blue">GoAid.in</span></span></span></a><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">; but does not nor is it intended to provide ambulance transportation services or any act that can be construed in any way as an act of an ambulance provider. GoAid is neither responsible nor liable for the acts and/or omissions of any transportation provider and/or any transportation services provided to you.</span></span></p>

<p><span style="font-size:18px"><span style="font-family:Arial,Helvetica,sans-serif"><strong>1. DEFINITIONS</strong></span></span></p>

<p><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">All capitalized terms in this Agreement, unless there is something in the subject matter or context inconsistent therewith, shall have the meaning ascribed to them below:</span></span></p>

<p><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><strong>&ldquo;Account&rdquo;</strong> shall mean the account created by Customer on the Website/Application for availing the Services provided by GoAid.</span></span></p>

<p><span style="font-size:18px"><strong><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">1.1. &ldquo;Advanced Life Support Ambulance (ALS)&rdquo;</span></strong></span><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"> shall mean an Ambulance which is capable of providing treatment of life-threatening medical emergencies through the use of techniques such as endo-tracheal intubations, administration of drugs or intravenous fluids, cardiac monitoring, and electrical therapy by a qualified person;</span></span></p>

<p><span style="font-size:18px"><strong><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">1.2. &ldquo;Ambulance&rdquo;</span></strong></span><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"> shall mean a vehicle, duly registered by the Transport Department, that is used for transporting injured to the nearby health facility in case of emergency, such as accident/disaster, etc.; as also for transporting patients in non-emergency situations such as scheduled visits to a doctor for treatment, routine physical examinations, X-ray or laboratory tests, transporting patients upon discharge, etc. ; </span></span></p>

<p><span style="font-size:18px"><strong><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">1.3. &ldquo;Ambulance Service Zone&rdquo;</span></strong></span><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"> shall mean the geographic area of the National Capital Region of Delhi; </span></span></p>

<p><span style="font-size:18px"><strong><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">1.4. &ldquo;Ambulance Transportation Services&rdquo;</span></strong></span><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><span style="font-size:18px"> </span>shall mean transporting injured to the nearby health facility and would include transport, such as scheduled visits to a doctor for treatment, routine physical examinations, X-ray or laboratory tests, transporting a woman for delivery to a hospital or after delivery and discharge to her home, transporting patients upon discharge from a hospital/nursing home, to another hospital/nursing home or to residence, etc.;</span></span></p>

<p><span style="font-size:18px"><strong><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">1.5. &ldquo;Applicable Law(s)&rdquo;</span></strong></span><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"> shall mean the relevant laws, rules, regulations, notifications, ordinances, bye-laws, guidelines, directions, policies, directivesmemorandums, etc. that are issued by the concerned department, tribunal, other governmental bodies, court(s), state/central government(s) with regards to the operation, running, maintenance of Ambulances;</span></span></p>

<p><span style="font-size:18px"><strong><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">1.6. &ldquo;Application&rdquo;</span></strong></span><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><span style="font-size:18px"> </span>shall mean the mobile application &ldquo;GoAid&rdquo; updated by GoAid from time to time. </span></span></p>

<p><span style="font-size:18px"><strong><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">1.7. &ldquo;Basic Life Support Ambulance (BLS)&rdquo;</span></strong></span><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"> means Ambulance which is capable of providing basic life support to the Users; </span></span></p>

<p><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><span style="font-size:18px">&ldquo;<strong>Customer or customer, You or you, Your or your&rdquo;</strong></span><br />
means a person who has an Account on the Website/Application;</span></span></p>

<p><span style="font-size:18px"><strong><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">1.9. &ldquo;Driver&rdquo;</span></strong></span><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"> shall mean and include such individuals as may be evaluated, appointed and trained by Transporter Provider associated with us to provide the Ambulance Transportation Services on its behalf and who have necessary permits and licenses to provide Ambulance Transportation Services transportation services within the Ambulance Service Zone; </span></span></p>

<p><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><span style="font-size:18px"><strong>&ldquo;E-Wallet&rdquo;</strong></span> shall mean a pre-paid instrument, which can be used to make payments;</span></span></p>

<p><span style="font-size:18px"><strong><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">1.11. &ldquo;Force Majeure Event&rdquo;</span></strong></span><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"> includes but is not limited to strikes, lockouts, labor disturbances, civil commotion, riots, war, acts of terrorism, major traffic disruption, action of any government or regulatory authority, fuel shortages, abnormal weather conditions at the location of services, abnormal business circumstances or any other cause beyond the reasonable control of the affected party which by exercise of reasonable diligence could not have been prevented or provided against;</span></span></p>

<p><span style="font-size:18px"><strong><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">1.12. &ldquo;GoAid&rdquo; or &ldquo;us&rdquo; or &ldquo;we&rdquo; or &ldquo;our&rdquo; </span></strong></span><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">shall mean Solution Hub. having its registered office at 7 UB , BUNGALOW Road ,Kamla nagar,Jawahar Nagar,NEW DELHI-110007, which expression shall, unless it be repugnant to the context or meaning thereof, be deemed to mean and include all its successors, affiliates and permitted assigns;</span></span></p>

<p><span style="font-size:18px"><strong><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">1.13. &ldquo;Need&rdquo;</span></strong></span><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><span style="font-size:18px"> </span>shall mean the travel in the Ambulance by the Customer facilitated through the Website/Application;</span></span></p>

<p><span style="font-size:18px"><strong><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">1.14. &ldquo;Patient Transport Vehicle&rdquo;</span></strong></span><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><span style="font-size:18px"> </span>shall mean a vehicle (vans, buses or other vehicles) used by Stable Patient for making non emergency calls such as scheduled visits to a physician&#39;s office for treatment, routine physical examinations, x-rays or laboratory tests, or is used for transporting patients upon discharge from a hospital or nursing home to a hospital or nursing home or residence, or attending to other non emergency calls. </span></span></p>

<p><span style="font-size:18px"><strong><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">1.15. &ldquo;Software&rdquo;</span></strong></span><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"> shall mean the mobile application, or the website, created and developed by Eutopia to provide a platform to connect Users to independent Ambulance Transportation Service providers;</span></span></p>

<p><span style="font-size:18px"><strong><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">1.16. &ldquo;Stable Patient&rdquo;</span></strong></span><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><span style="font-size:18px"> </span>is one whose condition can be expected to remain the same throughout the transport and for whom none of the criteria for emergency transport has been met. </span></span></p>

<p><span style="font-size:18px"><strong><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">1.17. &ldquo;Website&rdquo;</span></strong></span><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"> shall mean </span></span><a href="https://medulance.com/terms"><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><span style="color:blue">http://GoAid.in</span></span></span></a><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"> operated by GoAid or any other software that enables the use of the Application or such other URL as may be specifically provided by GoAid;</span></span></p>

<p><span style="font-size:18px"><strong><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">2. ELIGIBILITY </span></strong></span></p>

<p><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">You will be &ldquo;Eligible&rdquo; to use the Services only when you fulfil all of the following conditions: </span></span></p>

<p><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">(a) You have attained at least 18 (eighteen) years of age. </span></span></p>

<p><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">(b) You are competent to enter into a contract under the Applicable Laws.</span></span></p>

<p><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">As a minor if you wish to use the Service such services shall be availed by your legal guardian or parents who have registered as a user on Website/Application. GoAid reserves the right to terminate your registration and refuse to provide you with access to the Website/Application if it is brought to GoAid&#39;s notice or if it is discovered that you are under the age of 18 years. </span></span></p>

<p><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">If you reside in a jurisdiction that restricts the use of the Service because of age, or restricts the ability to enter into contracts such as this Terms of Use due to age, you must abide by such age limits. </span></span></p>

<p><span style="font-size:18px"><strong><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">3. YOUR ACCOUNT &amp; REGISTRATION OBLIGATIONS</span></strong></span></p>

<p><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">You understand and acknowledge that you can register on the Website/Application only after complying with the requirements of this Clause 3 and by entering all the requisite information require to register. </span></span></p>

<p><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">You shall ensure that all the information that you provide during registration is accurate, complete, current, valid and true and is updated from time to time. We shall bear no liability for false, incomplete, old or incorrect information provided by you. </span></span></p>

<p><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">You are solely responsible for maintaining the confidentiality of your information and will be liable for all activities and transactions that occur through your Account, whether initiated by you or any third party. Your Account cannot be transferred, assigned or sold to a third party. We shall not be liable for any loss that you may incur as a result of someone else using your password or Account, either with or without your knowledge. </span></span></p>

<p><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">You shall maintain and promptly update your information to keep it true, accurate, current and complete GoAid has the right but not the obligation to terminate this Agreement and your use of the Service at any time with or without notice.</span></span></p>

<p><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">You shall only access the Service using authorized means. It is your responsibility to check and ensure that you have downloaded the correct Software for your device. GoAid is not liable if you do not have a compatible device or if you have downloaded the wrong version of the Application and/or the Software to your device. The GoAid reserves the right not to permit you to use the Service should you use the Application and/or the Software with an incompatible or unauthorized device or for purposes other than which the Software and/or the Application is intended to be used.</span></span></p>

<p><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">We allow you to open only one Account in association with the information provided by you. In case of any unauthorized use of your Account please immediately reach Us at info@GoAid.in. </span></span></p>

<p><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">In case, you are unable to access your Account, please inform Us at info@GoAid.in and make a written request for blocking your Account. We will not be liable for any unauthorized transactions made through Your Account prior to the expiry of 48 hours after you have made a request in writing for blocking Your Account, and shall not have any liability in case of Force Majeure Event. </span></span></p>

<p><span style="font-size:18px"><strong><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">4. SERVICES </span></strong></span></p>

<p><strong><span style="font-size:16px"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">4.1. The Website/Application permits you to avail four types of Needs:</span></span></strong></p>

<p><span style="font-size:12px"><span style="font-family:Arial,Helvetica,sans-serif"><strong>a) Advanced Life Support Ambulance (ALS) </strong></span></span></p>

<p><span style="font-size:12px"><span style="font-family:Arial,Helvetica,sans-serif"><strong>b) Basic Life Support Ambulance (BLS) </strong></span></span></p>

<p><span style="font-size:12px"><span style="font-family:Arial,Helvetica,sans-serif"><strong>c) Patient Transport Vehicle </strong></span></span></p>

<p><span style="font-size:12px"><span style="font-family:Arial,Helvetica,sans-serif"><strong>d) Mortuary Vehicle </strong></span></span></p>

<p><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">The Service allows you to send a request through GoAid to book the above-mentioned Needs on the GoAid network. GoAid provides you the list of nearby hospital, physician, laboratory, mortuary, pharmacists you wanted to visit. However, we do not recommend, refer, endorse, or approve any such hospital, physician, laboratory, mortuary, pharmacists. </span></span></p>

<p><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">4.2. The Driver has sole and complete discretion to accept or reject each request for Service. If the Driver accepts a request, GoAid, notifies you and provides information regarding the Driver - including Driver name, Driver Photo, Vehicle license number, telephone contact details of the Driver and such other details as may be determined. </span></span></p>

<p><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">4.3. GoAid shall procure reasonable efforts to bring you into contact with a Driver, subject to the availability of Driver in or around your location at the moment of your request for such services. </span></span></p>

<p><span style="font-size:18px"><strong><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">5. CONFIRMATION OF BOOKING </span></strong></span></p>

<p><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">GoAid shall, upon receiving the booking request from you in the manner set out above, proceed to confirm or decline the booking based on the availability of Ambulance at the pickup time, which shall be informed to you vide an SMS or email. In the event the booking is confirmed, you shall check the booking details including but not limited to pick up time and pick up place, and if there is incorrect detail, the same needs to be informed to us immediately by calling us at_______. </span></span></p>

<p><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">You shall bear the consequences and damages for any delay that may be caused to you due to your failure to check the confirmation SMS or email or failure to inform GoAid of the incorrect details immediately. </span></span></p>

<p><span style="font-size:18px"><strong><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">6. PAYMENT</span></strong></span></p>

<p><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">6.1. You shall choose to pay for the Service Fee by either of the following two methods: </span></span></p>

<p><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">Cash payment: Cash payment towards the Need Fee after the completion of Need can be made to the Driver.</span></span></p>

<p><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">E-Wallet: GoAid offers you the facility of making an online payment through an E- Wallet powered by a third party payment processor (&ldquo;Payment Processor&rdquo;). The processing of payments, in connection with your use of the E-Wallet will be subject to the terms, conditions, and privacy policies of the Payment Processor that GoAid engages for the purpose. GoAid will not be responsible for any errors by the Payment Processor in any manner. Further, even in cases of E- Wallet payments, all Additional Fee (defined below) shall have to be paid by You in cash, to the authority or person concerned or if already paid by the Driver, to the Driver. </span></span></p>

<p><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">6.2. Once you have completed a journey using the Service, you are required to make payment in full to the Transportation Provider in cash or your payment will be deducted automatically from E-Wallet and is non- refundable. If you have any complaints in relation to the Transportation Provider, then that dispute must be taken up with the Transportation Provider directly.</span></span></p>

<p><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">6.3. All applicable taxes in respect of the Fare shall be borne and payable by you to the GoAid. </span></span></p>

<p><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">6.4. GoAid shall provide a receipt of the Need fee payable by you at the end of the Need. You may raise a request for a copy of the invoices from your Account. </span></span></p>

<p><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">6.5. Any payment related issue, except when such issue is due to an error or fault in the Website/Application, shall be resolved between You and the Payment Processor. GoAid shall not be responsible for any unauthorized use of Your E-Wallet during or after availing the Services on the Site. </span></span></p>

<p><span style="font-size:18px"><strong><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">7. REPRESENTATION &amp; WARRANTIES</span></strong></span></p>

<p><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">By using the Software or the Application, you agree that:</span></span></p>

<p><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">You will only use the Service for lawful purposes;</span></span></p>

<p><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">You will only use the Service for the purpose for which it is intended to be used;</span></span></p>

<p><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">You will not use the Application for sending or storing any unlawful material or for fraudulent purposes;</span></span></p>

<p><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">You will not use the Application and/or the Software to cause nuisance, annoyance, inconvenience or make fake bookings;</span></span></p>

<p><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">You shall not contact the Transportation Provider for purposes other than the Service;</span></span></p>

<p><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">You will not impair the proper operation of the network;</span></span></p>

<p><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">You shall not intentionally or unintentionally cause or attempt to cause damage to the Transportation Provider;</span></span></p>

<p><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">You will not try to harm the Service, Application and/or the Software in any way whatsoever;</span></span></p>

<p><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">You will not copy, or distribute the Software or other content without written permission from GoAid;</span></span></p>

<p><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">You will only use the Software and/or the Application for your own use and will not resell it to a third party;</span></span></p>

<p><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">You will keep secure and confidential your account password or any identification we provide you which allows access to the Service;</span></span></p>

<p><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">You will provide us with whatever proof of identity we may reasonably request or require;</span></span></p>

<p><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">You will only use an access point or data account (AP) which you are authorized to use;</span></span></p>

<p><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">You shall not employ any means to defraud the GoAid or enrich yourself, through any means, whether fraudulent or otherwise, through any event, promotion or campaign launched by the GoAid to encourage new subscription or usage of the Service by new or existing users;</span></span></p>

<p><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">You agree that the Service is provided on a reasonable effort basis; and</span></span></p>

<p><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">You agree that your use of the Service will be subject to the Go Aid&rsquo;s Privacy Policy as may be amended from time to time.</span></span></p>

<p><span style="font-size:18px"><strong><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">8. LICENSE</span></strong></span></p>

<p><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">Subject to your compliance with these Terms, GoAid grants you a limited, non-exclusive, non-sublicensable, revocable, non-transferrable license to: (i) access and use the Applications on your personal device solely in connection with your use of the Services; and (ii) access and use any content, information and related materials that may be made available through the Services, in each case solely for your personal, noncommercial use. Any rights not expressly granted herein are reserved by GoAid and GoAid&rsquo;s licensors.</span></span></p>

<p><span style="font-size:18px"><strong><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">9. DISCLAIMERS</span></strong></span></p>

<p><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">The GoAid Website/Application or any information or content or listings published thereon are provided &quot;AS IS&quot; without representations or warranties of any kind, whether express or implied. All implied warranties, including, without limitation, implied warranties of merchantability, fitness for a particular purpose, and non-infringement, are hereby expressly disclaimed. GoAid reserves the right to withdraw or delete any information from the GoAid Application at any time in its sole discretion without any notice to you.</span></span></p>

<p><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">GoAid does not guarantee or make any representations with respect to the correctness, completeness or accuracy of the information or details listed/provided by the Service Providers or any third party (including Unregistered Facility) through the GoAid Application. While GoAid has taken precautions to avoid inaccuracies in the content, this GoAid Application, all content, information, software, Services and related graphics are provided &quot;AS IS&quot;, without warranty of any kind.</span></span></p>

<p><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">GoAid does not guarantee uninterrupted or continued access to the GoAid Application. You need to ensure that high speed internet / data connection and GPS (location) services are enabled on your device from which the GoAid Application is intended to be used or accessed. Your access to the GoAid Application may also be suspended, or restricted due to technological / software glitches or bugs or security breaches or maintenance, or the introduction of new facilities or services or on account of interruptions of any nature whatsoever, at any time without prior notice to you. In such an event, you may, in your sole discretion, independently contact the Service Provider or the Unregistered Facility or the national emergency helpline / police helpline or initiate a request for an ambulance with such Service Provider or Unregistered Facility through telephone or any other modes/channels of communication at any time.</span></span></p>

<p><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">GoAid will strive to meet the highest technical standards and shall not be liable in the event of any loss of your data/information available through the GoAid Application, injury, loss or death to any user for any reason whatsoever, in connection with your use of the GoAid Application (or any of its functionalities including the Pill Reminder).</span></span></p>

<p><span style="font-size:18px"><strong><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">10. INTELLECTUAL PROPERTY OWNERSHIP</span></strong></span></p>

<p><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">10.1. The GoAid and its licensors, where applicable, shall own all right, title and interest, including all related intellectual property rights, in and to the Software and/or the Application and by extension, the Service and any suggestions, ideas, enhancement requests, feedback, recommendations or other information provided by you or any other party relating to the Service. </span></span></p>

<p><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">10.2. The Terms of Use do not constitute a sale agreement and do not convey to you any rights of ownership in or related to the Service, Software and/or the Application, or any intellectual property rights owned by the GoAid and/or its licensors. The GoAid name, the GoAid logo, the Service, the Software and/or the Application and the Transportation Providers&#39; logos and the product names associated with the Software and/or the Application are trademarks of the GoAid or third parties, and no right or license is granted to use them. For the avoidance of doubt, the term Software and Application herein shall include its respective components, processes and design in its entirety.</span></span></p>

<p><span style="font-size:18px"><strong><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">11. LIABILITY</span></strong></span></p>

<p><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">11.0. Any claims against GoAid by you shall in any event be limited to the aggregate amount of all amounts actually paid by and/or due from you in utilising the service during the event giving rise to such claims. In no event shall GoAid and/or its licensors be liable to you or anyone for any direct, indirect, punitive, economic, future special, exemplary, incidental, consequential or other damages or losses of any type or kind (including personal injury, emotional distress and loss of data, goods, revenue, profits, use or other economic advantage). GoAid and/or its licensors shall not be liable for any loss, damage or injury which may be incurred by or caused to you or to any person for whom you have booked the service for, including but not limited to loss, damage or injury arising out of, or in any way connected with the service, application and/or the software, including but not limited to the use or inability to use the service, application and/or the software, any reliance placed by you on the completeness, accuracy or existence of any advertising, or as a result of any relationship or transaction between you and any third party provider, advertiser or sponsor whose advertising appears on the website or is referred to by the service, application and/or the software, even if GoAid and/or its licensors have been previously advised of the possibility of such damages.</span></span></p>

<p><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">GoAid does not and will not assess nor monitor the suitability, legality, ability, movement or location of any third party providers including Transportation Providers, advertisers and/or sponsors and you expressly waive and release GoAid from any and all liability, claims or damages arising from or in any way related to the third party providers including Transportation Providers, advertisers and/or sponsors. GoAid will not be a party to disputes, negotiations of disputes between you and such third party providers including Transportation Providers, advertisers and/or sponsors. We cannot and will not play any role in managing payments between you and the third party providers, including Transportation Providers, advertisers and/or sponsors. Responsibility for the decisions you make regarding services and products offered via the service, software and/or the application (with all its implications) rests solely with and on you. You expressly waive and release GoAid from any and all liability, claims, causes of action, or damages arising from your use of the service, software and/or the application, or in any way related to the third parties including Transportation Providers, advertisers and/or sponsors introduced to you by the service, software and/or the application.</span></span></p>

<p><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">The quality of the service is entirely the responsibility of the Transportation Provider who ultimately provides such transportation services to you. You understand, therefore, that by using the service, you may be exposed to transportation that is potentially dangerous, offensive, harmful to minors, unsafe or otherwise objectionable, and that you use the service at your own risk.</span></span></p>

<p><span style="font-size:18px"><strong><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">12. INDEMNITY</span></strong></span></p>

<p><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">12.1. You agree to indemnify and hold GoAid and its officers, directors, employees and agents harmless from any and all claims, demands, losses, liabilities, and expenses (including attorneys&rsquo; fees) arising out of or in connection with: a) your use of Services; (b) Your breach of Terms of Use and (c) Your violation of any third party rights.</span></span></p>

<p><span style="font-size:18px"><strong><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">13. SEVERABILITY</span></strong></span></p>

<p><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">If any of the provisions, or portions thereof, of these Terms of Use are found to be invalid under any applicable statute or rule of law, then, that provision notwithstanding, these Terms of Use shall remain in full force and effect and such provision or portion thereof shall be deemed omitted.</span></span></p>

<p><span style="font-size:18px"><strong><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">14. WAIVER</span></strong></span></p>

<p><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">Any waiver of any provision of these Terms of Use, or a delay by any party in the enforcement of any right hereunder, shall neither be construed as a continuing waiver nor create an expectation of non-enforcement of that or any other provision or right.</span></span></p>

<p><span style="font-size:18px"><strong><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">15. GOVERNING LAWS &amp; JURISDICATION</span></strong></span></p>

<p><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">15.1. These Terms of Use are governed by the laws of India. Any disputes/claims arising out of your use of the GoAid Application shall be submitted to the exclusive jurisdiction of the courts at Delhi.</span></span></p>

<p><span style="font-size:18px"><strong><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">16. PRIVACY POLICY</span></strong></span></p>

<p><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">Please review our Privacy Policy, which also governs your access or use of the GoAid Application.</span></span></p>

<p><span style="font-size:18px"><strong><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">17. COMMUNICATIONS</span></strong></span></p>

<p><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">You agree and acknowledge that GoAid may communicate with you by e-mail, SMS, push notifications, telephone or by posting notices on the GoAid Website/Application or through any other mode of communication. You agree that all terms/agreements, notices, disclosures and other communications that GoAid provides to you will electronically satisfy any legal requirement that such communications be in writing.</span></span></p>

<p><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">For contractual purposes, you agree and consent to receive communications from us (as set out in this Section) with respect to the GoAid Website/Application including information regarding your account or updates/changes to the GoAid Application, and/or any functionalities / features available on the GoAid Application or any information which GoAid or Transportation Provider so authorized by GoAid as per the Privacy Policy communicates to you from time to time (including lifestyle, disease or health related notifications). </span></span></p>

<p><span style="font-size:18px"><strong><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">18. USE OF GOOGLE MAPS</span></strong></span></p>

<p><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">18.1. You agree and acknowledge that mapping service on the GoAid Application is provided through the Google Maps API by Google Inc., located at 1600 Amphitheatre Parkway, Mountain View, CA 94043, United States. By downloading, installing or using the GoAid Application, you agree to be bound by the Google Terms of Use (http://maps.google.com/help/ terms_maps.html).</span></span></p>

<p><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">18.2. You agree and acknowledge that it is your sole responsibility to review, determine the applicability and comply with the Google Terms of Service, as may be revised from time to time. GoAid will not be responsible for any liability or loss/damage caused or suffered by you on account of your reliance on the mapping/navigation service made available by Google Maps through the GoAid Application.</span></span></p>

<p>&nbsp;</p>

			</div>
		</div>
	</div>
</section>
<?php include ('footer.php');?>